# Generated by Django 5.0.2 on 2025-01-01 10:41

import data_related.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 10 digits allowed.", regex='^\\+?1?\\d{9,10}$')])),
                ('email', models.EmailField(max_length=254)),
                ('inquiry_type', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('position', models.CharField(max_length=100)),
                ('skills', models.TextField()),
                ('education_level', models.CharField(max_length=20)),
                ('years_experience', models.PositiveIntegerField()),
                ('portfolio_links', models.TextField(blank=True)),
                ('additional_info', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_marathi', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('description_marathi', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='jobs/')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('meta_title', models.CharField(blank=True, help_text='SEO Meta Title', max_length=60)),
                ('meta_description', models.CharField(blank=True, help_text='SEO Meta Description', max_length=160)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('main_image', models.ImageField(upload_to=data_related.models.product_image_path)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_marathi', models.CharField(blank=True, max_length=255, null=True)),
                ('model', models.CharField(max_length=255)),
                ('model_marathi', models.CharField(blank=True, max_length=255, null=True)),
                ('description_marathi', models.TextField(blank=True, null=True)),
                ('yt_link', models.URLField(blank=True, null=True)),
                ('yt_tagline', models.CharField(blank=True, max_length=255, null=True)),
                ('yt_tagline_marathi', models.CharField(blank=True, max_length=255, null=True)),
                ('booking_tagline', models.CharField(blank=True, max_length=255, null=True)),
                ('booking_tagline_marathi', models.CharField(blank=True, max_length=255, null=True)),
                ('warrenty', models.CharField(max_length=50)),
                ('technical_details_model_name', models.CharField(max_length=255)),
                ('technical_details_model_name_marathi', models.CharField(blank=True, max_length=255, null=True)),
                ('technical_details_brand_name', models.CharField(max_length=255)),
                ('technical_details_brand_name_marathi', models.CharField(blank=True, max_length=255, null=True)),
                ('technical_details_application', models.TextField()),
                ('technical_details_application_marathi', models.TextField(blank=True, null=True)),
                ('technical_details', models.JSONField()),
                ('technical_details_marathi', models.JSONField(blank=True, null=True)),
                ('demo_tagline', models.CharField(blank=True, max_length=255, null=True)),
                ('demo_tagline_marathi', models.CharField(blank=True, max_length=255, null=True)),
                ('demo_yt_link', models.URLField(blank=True, null=True)),
                ('discounted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('installation_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('out_of_stock', 'Out of Stock'), ('coming_soon', 'Coming Soon'), ('discontinued', 'Discontinued')], default='active', max_length=20)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('min_order_quantity', models.IntegerField(default=1)),
                ('max_order_quantity', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeatureImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=data_related.models.feature_image_path)),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('caption_marathi', models.CharField(blank=True, max_length=255, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_images', to='data_related.product')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_number', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 10 digits allowed.", regex='^\\+?1?\\d{9,10}$')])),
                ('alternate_phone', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 10 digits allowed.", regex='^\\+?1?\\d{9,10}$')])),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('installation_required', models.BooleanField(default=False)),
                ('installation_address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='data_related.product')),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=data_related.models.additional_image_path)),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('caption_marathi', models.CharField(blank=True, max_length=255, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='data_related.product')),
            ],
        ),
    ]
